import type { Metadata } from "next";
import { Be_Vietnam_Pro } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/contexts/auth-context";
import { MessageProvider } from "@/contexts/message-context";
import Navbar from "@/components/Navbar";
import GlobalCallManager from "@/components/GlobalCallManager";
import GlobalMatchNotifier from "@/components/GlobalMatchNotifier";

const beVietnamPro = Be_Vietnam_Pro({
  subsets: ["vietnamese"],
  weight: ["400", "700"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// layout.tsx
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${beVietnamPro.className} antialiased`}>
        <AuthProvider>
          <MessageProvider>
            <GlobalMatchNotifier />
            {/* XÓA pt-20 Ở ĐÂY. Để layout tràn màn hình */}
            <div className="flex flex-col min-h-screen relative">
              <Navbar />
              {/* Thẻ main này KHÔNG được có pt-20 hay pt-24 */}
              <main className="flex-1">
                {children}
              </main>
              <GlobalCallManager />
            </div>
          </MessageProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
